### ISSUE TITLE
[Bug] Visual Formatting Issue

### ISSUE THREAD

**Issue by drardin** [villanovachile/truthtally#24]
**Describe the bug**
The appearance of the buttons are reduced to the height of the text. The placement of the buttons are near where they should be, relative to other visual elements. Lower half portion of the page is blank.

**To Reproduce**
1. Create a ranked list
2. Generate pairs for comparison

**Expected behavior**
Buttons are typically around ~40% of the height of the viewport. (This is only a guess)

**Screenshots**
![image](https://user-images.githubusercontent.com/81466808/230237891-5e3eaeb6-0a98-45fe-a532-33ea99b6d38d.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.3.1
 - Browser: Safari (native client)
 - User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1

**Comment by villanovachile** [comment]
Thanks for getting this reported!

This only occurs on mobile and when creating a new list from the root domain. If creating a list from `/list/` or if loading a saved list and ranking it, the issue doesn't occur.

I've tracked it down to an issue with how the app is structured in a non-compatible way with Next.js. The div `__next` is automatically injected into the DOM tree and should be the root div.  

Currently this is how it appears in its current state:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/65082164/230249759-6526cdab-e2e0-44e4-a825-fae5ebfaaf56.png">


The `__next` div is nested in the `main-container` div and is therefore breaking the height property that is defined in the `truthtally-container` div.

I've worked on creating a layout component that ensures `__next` div is the root div and a PR will be coming shortly!
