### ISSUE TITLE
Tags need to allow dashes or spaces

### ISSUE THREAD

**Issue by ash1eygrace** [villanovachile/truthtally#29]
Can we please have dashes in tags <3

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/29527450/233238186-93c71b6a-9890-4f6d-a5c7-7535e64ff9e8.png">

Optionally allow spaces and automatically add the dash: 

<img width="776" alt="image" src="https://user-images.githubusercontent.com/29527450/233238222-5428c4b5-d51b-476c-85ea-ab4fedc70f1f.png">

**Comment by villanovachile** [comment]
Resolved with d91daa3ea380f2f080ad1656ca84a9c9d6382bcf
